version: 2.1

orbs:
  node: circleci/node@4.7.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.17.5

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to NPM
          command: yarn publish --access public --non-interactive

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
  production:
    jobs:
      - test:
          filters:
            &filters-production # this yaml anchor is setting these values to "filters-production"
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          context: NPM_Publish
          requires:
            - test
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
