export type zNA = string;
export type zNAId = string;
export type zDAOId = string;
export type ENS = string;
export type ENSId = string;
export type ProposalId = string;
export type VoteId = string;
export type Choice = number;
export type Maybe<T> = T | undefined;
