/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IZNSHub, IZNSHubInterface } from "../IZNSHub";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "domainId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IZNSHub__factory {
  static readonly abi = _abi;
  static createInterface(): IZNSHubInterface {
    return new utils.Interface(_abi) as IZNSHubInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZNSHub {
    return new Contract(address, _abi, signerOrProvider) as IZNSHub;
  }
}
