/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IChildChainManagerInterface extends utils.Interface {
  contractName: "IChildChainManager";
  functions: {
    "childToRootToken(address)": FunctionFragment;
    "rootToChildToken(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "childToRootToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "rootToChildToken",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "childToRootToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootToChildToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IChildChainManager extends BaseContract {
  contractName: "IChildChainManager";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IChildChainManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    childToRootToken(
      _child: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    rootToChildToken(
      _root: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  childToRootToken(_child: string, overrides?: CallOverrides): Promise<string>;

  rootToChildToken(_root: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    childToRootToken(
      _child: string,
      overrides?: CallOverrides
    ): Promise<string>;

    rootToChildToken(_root: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    childToRootToken(
      _child: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rootToChildToken(
      _root: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    childToRootToken(
      _child: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rootToChildToken(
      _root: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
